name: Ubuntu 20.04

# Dependencies of this package
env:
  UBUNTU_APT: ${{ 'libgtk-3-dev gir1.2-gtk-3.0 gir1.2-gtksource-3.0 libcogl-pango-dev libcogl-path-dev libcogl-dev libpango1.0-dev gir1.2-pango-1.0 libgdk-pixbuf2.0-dev gir1.2-gdkpixbuf-2.0 libgraphene-1.0-dev gir1.2-graphene-1.0 libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq' }}

on:
  push:
    branches:
      - monorepo
      - development
      - main
  pull_request:
    branches:
      - monorepo
      - development
      - main

jobs:
  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: YOCKOW/Action-setup-swift@v1
        with:
          swift-version: '5.6.1'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Update package repository
        run: sudo apt-get update

      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftGtk
        uses: actions/checkout@v2
        with:
          path: SwiftGtk

      - name: Build SwiftGtk
        run: |
          cd SwiftGtk
          swift build
          cd ..

#      - name: Test SwiftGtk
#        run: |
#          cd SwiftGtk
#          swift test
#          cd ..

      - name: Remove unneeded files and archive artefacts
        run: |
          cd SwiftGtk
          swift package clean
          rm -rf .build/repositories
          cd ..

#     - name: 'Upload Artefact'
#       uses: actions/upload-artifact@v2
#       with:
#         name: build-artefact-20.04-5.3
#         path: |
#           SwiftGtk/Sources/
#         retention-days: 1
