name: Linux (gtk4)

# Dependencies of this package
env:
  UBUNTU_APT: ${{ 'libgtk-4-dev libatk1.0-dev gir1.2-atk-1.0 libpango1.0-dev gir1.2-pango-1.0 libgdk-pixbuf2.0-dev gir1.2-gdkpixbuf-2.0 libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq xvfb' }}

on:
  push:
    branches: [gtk4-development, gtk4]
  pull_request:
    branches: [gtk4-development, gtk4]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: ${{ matrix.os }} (Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            swift: "6.1"
          - os: ubuntu-22.04
            swift: "6.1"
          - os: ubuntu-22.04
            swift: "5.10.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: SwiftGtk

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}

      - name: Swift version
        run: swift --version

      - name: Fetch Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y $UBUNTU_APT

      - name: Build
        run: cd SwiftGtk && swift build

      - name: Test
        run: cd SwiftGtk && xvfb-run -a swift test
